before:
  hooks:
    - git config --global --add safe.directory /
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/whereami/main.go
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: "386"
    binary: "{{ .ProjectName }}_v{{ .Version }}"
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    rlcp: true
    files:
      - README.md
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256


release:
  # github:
  #   owner: s-yakubovskiy
  #   name: whereami
  draft: false
  disable: false
changelog:
  skip: true
